language: python
python:
  - "3.6.3"
# command to install dependencies
install: 
  - pip install -r requirements.txt
# command to run tests
script:
     - "python test_recipecategories.py"
     - "python test_recipes.py"
     - "python test_userclass.py"
     - "coverage run test_recipecategories.py"
     - "coverage run test_recipes.py"
     - "coverage run test_userclass.py"
after_success:
  coveralls